name: sanitizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sanitizer:
    runs-on: ubuntu-latest

    name: sanitizer
    steps:
      - uses: actions/checkout@v2

      - name: Run AddressSanitizer
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          gcc --version
          g++ --version
          clang --version
          clang++ --version
