name: Valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  valgrind:
    runs-on: ubuntu-latest

    name: 42valgrind
    steps:
      - uses: actions/checkout@v2

      - name: Run Makefile
        run: make -C ex00 re

      - name: 42valgrind Leak checker
        uses: solareenlo/42valgrind-action@v1.0.0
        with:
          flags: ''
